name: Learning Github Actions
run-name: Learning Github Actions
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby Pkgs
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Run script
        run: hello.rb
